spring:
  datasource:
    url: 'jdbc:mysql://localhost/webmvc?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai'
    username: 'root'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    password: 'admin123456!@#'
    hikari:
      connection-test-query: select 1
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: 'org.hibernate.dialect.MySQL8Dialect'
    hibernate:
      use-new-id-generator-mappings: true
