server:
  port: 8886
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: '@datasource.url@'
    username: '@datasource.username@'
    driver-class-name: '@datasource.driver@'
    password: '@datasource.password@'
    hikari:
      connection-test-query: select 1
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: '@datasource.platform@'
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: update
security:
  oauth2:
    resource:
      user-info-uri: '@user.info.url@'