spring:
  profiles:    active:    - lidong
  security:
    oauth2:
      client:
        registration:
          oauth2:
            client-id: zuul
            client-secret: 123456
            authorization-grant-type: authorization_code
            # TODO 需要配合nginx的redirect_rewrite参数才能实现正确的请求，需要解决redirect_uri问题
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          oauth2:
            user-info-uri: http://127.0.0.1:8887/oauth/users/current
            authorization-uri: http://127.0.0.1:8887/oauth/authorize
            token-uri: http://127.0.0.1:8887/oauth/token
            user-name-attribute: username
  cloud:    gateway:
      default-filters:      - TokenRelay= # 复制token到上游服务器
      routes:      - id: files
        uri: http://127.0.0.1:8886
        filters:
        - StripPrefix=1 # 截断路径中多余的部分
        predicates:        - Path=/d/files**/**
      - id: uap
        uri: http://127.0.0.1:8887
        filters:
        - StripPrefix=1        predicates:        - Path=/u/**