server:
  port: 8080
spring:
  datasource:    url: 'jdbc:mysql://localhost/gateway?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    username: 'root'
    password: 'admin123456!@#'  jpa:    database-platform: 'org.hibernate.dialect.MySQL8Dialect'      show-sql: true
    generate-ddl: true
    hibernate:      use-new-id-generator-mappings: true
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://127.0.0.1:8887/oauth/users/current
      client:
        registration:
          oauth2:
            client-id: zuul
            client-secret: 123456
            authorization-grant-type: authorization_code
            # TODO 需要配合nginx的redirect_rewrite参数才能实现正确的请求，需要解决redirect_uri问题
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          oauth2:
            user-info-uri: http://127.0.0.1:8887/oauth/users/current
            authorization-uri: http://127.0.0.1:8887/oauth/authorize
            token-uri: http://127.0.0.1:8887/oauth/token
            user-name-attribute: username
  cloud:
    gateway:
      default-filters:
      - TokenRelay= # 复制token到上游服务器
      routes:
      - id: files
        uri: http://127.0.0.1:8886
        filters:
        - StripPrefix=1 # 截断路径中多余的部分
        predicates:
        - Path=/d/files**/**
      - id: uap
        uri: http://127.0.0.1:8887
        filters:
        - StripPrefix=1
        predicates:
        - Path=/u/**