spring:
  profiles:    active:    - lidong
  security:
    oauth2:
      client:
        registration:
          oauth2:
            client-id: zuul
            client-secret: 123456
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            client-authentication-method: 
        provider:
          oauth2:
            user-info-uri: http://127.0.0.1:8887/oauth/users/current
            authorization-uri: http://127.0.0.1:8887/oauth/authorize
            token-uri: http://127.0.0.1:8887/oauth/token
            user-name-attribute: username            
#            user-info-authentication-method: POST # 指定通过post获取用户信息  cloud:    gateway:      routes:      - id: files
        uri: http://127.0.0.1:8886/files/1
        filters:        - StripPrefix=1
        predicates:        - Path=/d/files**/**