server:
  port: 8080
spring:
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://localhost/server_gateway?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai'
    username: 'root'
    password: 'Abc.123456'
    hikari:
      connection-test-query: Select 1
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: 'org.hibernate.dialect.MySQL8Dialect'
    hibernate:
      use-new-id-generator-mappings: true
  security:
    oauth2:
      client:
        registration:
          oauth2:
            client-id: app
            client-secret: 123456
            authorization-grant-type: authorization_code
            scope:
              - userinfo
            redirect-uri: "{xForwardedProto}://{xForwardedHost}{prefix}login/oauth2/code/{registrationId}"
        provider:
          oauth2:
            user-info-uri: http://127.0.0.1:8887/oauth2/userinfo
            authorization-uri: http://127.0.0.1:8887/oauth2/authorize
            token-uri: http://127.0.0.1:8887/oauth2/token
            user-name-attribute: username
  cache:
    type: jcache
    jcache:
      config: classpath:config/ehcache.xml
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: uap
          uri: http://127.0.0.1:8887
          predicates:
            - Path=/u/**
          filters:
            - StripPrefix=1
