spring:
  datasource:
    url: '@datasource.url@'
    username: '@datasource.username@'
    driver-class-name: 'org.mariadb.jdbc.Driver'
    password: '@datasource.password@'
    hikari:
      connection-test-query: select 1
  jpa:
    show-sql: false
    generate-ddl: true
    database-platform: '@datasource.platform@'
    hibernate:
      use-new-id-generator-mappings: true
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
        - info